// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA71tZIUuUrwa3QLyiNubmskRU9EdumhwM',
    appId: '1:54598466760:web:7a9d46c8b5bf4f349cf9fd',
    messagingSenderId: '54598466760',
    projectId: 'rotaractapp',
    authDomain: 'rotaractapp.firebaseapp.com',
    storageBucket: 'rotaractapp.firebasestorage.app',
    measurementId: 'G-ZWDPPC96CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGrERR7RqjiSypjHc6As6T4Ai85PQiC-E',
    appId: '1:54598466760:android:cea61f966e8cc0129cf9fd',
    messagingSenderId: '54598466760',
    projectId: 'rotaractapp',
    storageBucket: 'rotaractapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn5f7H7mMB3d4hDbYSwyjDq6PcQca8q5o',
    appId: '1:54598466760:ios:8a0263f3d127d3f09cf9fd',
    messagingSenderId: '54598466760',
    projectId: 'rotaractapp',
    storageBucket: 'rotaractapp.firebasestorage.app',
    iosBundleId: 'com.example.rotaractApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn5f7H7mMB3d4hDbYSwyjDq6PcQca8q5o',
    appId: '1:54598466760:ios:8a0263f3d127d3f09cf9fd',
    messagingSenderId: '54598466760',
    projectId: 'rotaractapp',
    storageBucket: 'rotaractapp.firebasestorage.app',
    iosBundleId: 'com.example.rotaractApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA71tZIUuUrwa3QLyiNubmskRU9EdumhwM',
    appId: '1:54598466760:web:5f95249045f8d1b29cf9fd',
    messagingSenderId: '54598466760',
    projectId: 'rotaractapp',
    authDomain: 'rotaractapp.firebaseapp.com',
    storageBucket: 'rotaractapp.firebasestorage.app',
    measurementId: 'G-M6WHXN9RDH',
  );
}
